sudo: required

services:
  - docker
env:
  global:
    - IMAGE_NAME=logops/log-store
    - VERSION=1.0.0-SNAPSHOT

language: groovy
install: true
os: linux
dist: trusty
jdk: oraclejdk11

stages:
  - name: unit-test
  if: (NOT (branch IN (master, stage, develop)))
  - name: test-all
  if: (branch IN (master, stage, develop))
  - name: build-deploy
  if: (branch IN (master, stage, develop))

jobs:
  include:
    - stage: unit-test
      name: "unit-test"
      script: "echo Only performing unit tests && ./gradlew test --tests logstore.unit*"
    
    - stage: test-all
      name: "test-all"
      script: "echo Running all tests && ./gradlew build -s"
      
    - stage: build-deploy
      name: "build-deploy"
      script:
        - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
        - docker build -t "${IMAGE_NAME}:${VERSION}" .
        - docker push "${IMAGE_NAME}:${VERSION}"
        - "echo Deployment stuff"
