language: groovy
install: true

os: linux
dist: trusty
jdk: oraclejdk11

jobs:
  include:
    - stage: unit-test
      script: "./gradlew test log-store.controller*" #remove if it works
      if: (NOT (branch IN (master, stage, develop)))
    - stage: test-all
      script: "./gradlew build -s"
      if: (branch IN (master, stage, develop))
    - stage: deploy
      script: "echo deployment stuff"
      if: (branch IN (master, stage, develop))    

