version: '3.3'
services:
  logstore:
    image: docker.io/logops/${LOG_STORE_IMAGE:-log-store}:${LOG_STORE_VERSION:-1.0.0}
    container_name: logstore
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "8079:8080"
    networks:
      - logstore
    environment:
      ELASTIC_HOST: http://esdb:9200
    depends_on:
      - esdb

  esdb:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: esdb
    networks:
      - logstore
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "cluster.name=esdb"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.cors.enabled=true"
      # - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
    volumes:
      # create a data_db dir, likely in /var/lib/docker/volumes
      - "esdb:/usr/share/elasticsearch/data"

volumes:
  esdb:

networks:
  logstore:

