apiVersion: v1
kind: Service
metadata:
  name: log-store-esdb-service
spec:
  selector:
    app: log-store-esdb
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-store-esdb-deployment
  labels:
    app: log-store-esdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-store-esdb
  template:
    metadata:
      labels:
        app: log-store-esdb
    spec:
      containers:
      - name: log-store-esdb
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        ports:
        - containerPort: 9200
        env:
        - name: "discovery.type"
          value: "single-node"
        - name: "cluster.name"
          value: "log-store-esdb"
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        - name: "http.cors.enabled"
          value: "true"
        - name: "xpack.security.enabled"
          value: "false"
