apiVersion: v1
kind: Service
metadata:
  name: log-store-service
spec:
  selector:
    app: log-store
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-store-deployment
  labels:
    app: log-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-store
  template:
    metadata:
      labels:
        app: log-store
    spec:
      containers:
      - name: log-store
        image: logops/log-store:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ELASTIC_HOST
          value: http://log-store-esdb-service:9200
